### ISSUE TITLE
some questions about rgb/nir image fusion

### ISSUE THREAD

**Issue by Tangzl7** [kimphys/DIFNet.pytorch#1]
Hello, I would like to get the experiment result of the visible and near-infrared image fusion in the paper, can you provide the model file? Or I train by myself, but I have a few questions. The paper mentions that the image patch size for training is 40*40, but the image is directly scaled to 256*256 in the code. Can I train directly without cropping? If not, do I need to crop a 40*40 image block from the original image, or crop it from the scaled image?

**Comment by Z-TTY** [comment]
Hello, I am also asking this question, have you solved it please?

**Comment by Tangzl7** [comment]
> Hello, I am also asking this question, have you solved it please?

I can get the fused image that combines texture information through training, but there are differences from the paper. The color of the fusion result in the paper is different from the original image (it looks like a contrast enhancement). The color of the fusion result I get is the same as the original image. I contacted the author but have not heard back.

**Comment by Tangzl7** [comment]
> Hello, I am also asking this question, have you solved it please?

My training method is to randomly crop 1/4 size of the original image on the original image and resize it to 40*40 as the training data.

**Comment by Z-TTY** [comment]
I went straight to the 256 size TNO image and didn't crop it, and got a terrible fusion result


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kimphys/DIFNet.pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月27日(星期一) 下午5:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kimphys/DIFNet.pytorch] some questions about rgb/nir image fusion (Issue #1)





  
Hello, I am also asking this question, have you solved it please?
  
I can get the fused image that combines texture information through training, but there are differences from the paper. The color of the fusion result in the paper is different from the original image (it looks like a contrast enhancement). The color of the fusion result I get is the same as the original image. I contacted the author but have not heard back.

**Comment by Z-TTY** [comment]
Can you share your code for my reference?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kimphys/DIFNet.pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月27日(星期一) 下午5:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kimphys/DIFNet.pytorch] some questions about rgb/nir image fusion (Issue #1)





  
Hello, I am also asking this question, have you solved it please?
  
My training method is to randomly crop 1/4 size of the original image on the original image and resize it to 40*40 as the training data.

**Comment by Tangzl7** [comment]
> Can you share your code for my reference?
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "kimphys/DIFNet.pytorch" ***@***.***&gt;; 发送时间:&nbsp;2023年3月27日(星期一) 下午5:52 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [kimphys/DIFNet.pytorch] some questions about rgb/nir image fusion (Issue #1) Hello, I am also asking this question, have you solved it please? My training method is to randomly crop 1/4 size of the original image on the original image and resize it to 40*40 as the training data. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

You can try out my image processing first (so we can have some discussions later). If it doesn't work, I can share my code.

**Comment by Z-TTY** [comment]
Ok thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kimphys/DIFNet.pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月27日(星期一) 晚上6:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kimphys/DIFNet.pytorch] some questions about rgb/nir image fusion (Issue #1)





  
Can you share your code for my reference?
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "kimphys/DIFNet.pytorch" @.&gt;; 发送时间:&nbsp;2023年3月27日(星期一) 下午5:52 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [kimphys/DIFNet.pytorch] some questions about rgb/nir image fusion (Issue #1) Hello, I am also asking this question, have you solved it please? My training method is to randomly crop 1/4 size of the original image on the original image and resize it to 4040 as the training data. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.**&gt;
  
You can try out my image processing first (so we can have some discussions later). If it doesn't work, I can share my code.
